version: '2'

services:

    application:
        build: .
        working_dir: /var/www
        ports:
            - 80:80
        volumes:
            - ./opt/php/dev/conf.d:/usr/local/etc/php/conf.d
            - ./opt/php/dev/php.ini:/usr/local/etc/php/php.ini
            - ./opt/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        depends_on:
            - database
            - redis

    cache_and_logs:
        image: busybox
        volumes:
            - /var/www/build
            - /var/www/app/cache
            - /var/www/app/logs
            - /var/www/web/assets
            - /var/www/web/bundles
            - /var/www/web/static
            - /var/www/web/uploads
            - /var/www/web/screenshots

    blackfire:
        image: blackfire/blackfire:latest
        environment:
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN
            - BLACKFIRE_LOG_LEVEL=4

    node:
        image: node:5.6
        command: ./opt/node/run.sh
        working_dir: /var/www
        volumes:
            - .:/var/www

    database:
        image: postgres
        environment:
            - POSTGRES_DB=ppl
            - POSTGRES_PASSWORD=ppl
            - POSTGRES_USER=ppl

    elasticsearch:
        image: willdurand/elk
        volumes:
            - ./opt/elk/logstash:/etc/logstash
            - ./opt/elk/logstash/patterns:/opt/logstash/patterns

    redis:
        image: redis

    beanstalkd:
        image: schickling/beanstalkd

    varnish:
        image: million12/varnish:latest
        volumes:
            - ./opt/varnish/dev/default.vcl:/etc/varnish/default.vcl
