version: '2'

services:
    application:
        image: my-registry.com/pplweb:%BUILD_TAG%
        environment:
            SYMFONY_ENVIRONMENT: test
        working_dir: /var/www
        entrypoint: ./opt/deployment/test/start.sh
        ports:
            - 80
        depends_on:
            - database
            - elasticsearch
            - redis
            - cache_and_logs

    database:
        extends:
            file: docker-compose.base.yml
            service: database

    elasticsearch:
        extends:
            file: docker-compose.base.yml
            service: elasticsearch
        volumes_from:
            - cache_and_logs

    redis:
        extends:
            file: docker-compose.base.yml
            service: redis

    beanstalkd:
        extends:
            file: docker-compose.base.yml
            service: beanstalkd

    varnish:
        extends:
            file: docker-compose.base.yml
            service: varnish
        depends_on:
            - application
