version: '2'

volumes:
    screenshots:
        driver: local
    build:
        driver: local

services:
    application:
        image: registry.com/pplweb:%BUILD_TAG%
        environment:
            SYMFONY_ENVIRONMENT: test
        working_dir: /var/www
        entrypoint: ./opt/deployment/test/start.sh
        ports:
            - 80
        volumes:
            - ./opt/php/dev/conf.d:/usr/local/etc/php/conf.d
            - ./opt/php/dev/php.ini:/usr/local/etc/php/php.ini
            - ./opt/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
            - ./build:/var/www/build
            - ./web/screenshots:/var/www/web/screenshots
        depends_on:
            - database
            - elasticsearch
            - redis
            - beanstalkd
            - cache_and_logs
            - phantomjs

    cache_and_logs:
        extends:
            file: docker-compose.base.yml
            service: cache_and_logs

    database:
        extends:
            file: docker-compose.base.yml
            service: database
        ports:
            - 5432

    elasticsearch:
        extends:
            file: docker-compose.base.yml
            service: elasticsearch
        ports:
            - 80
            - 9200
        volumes_from:
            - cache_and_logs

    redis:
        extends:
            file: docker-compose.base.yml
            service: redis

    beanstalkd:
        extends:
            file: docker-compose.base.yml
            service: beanstalkd
        ports:
            - 11300

    varnish:
        extends:
            file: docker-compose.base.yml
            service: varnish
        ports:
            - 80
        depends_on:
            - application

   selenium:
       image: selenium/standalone-firefox-debug:2.52.0
       environment:
           - SCREEN_WIDTH=1920
           - SCREEN_HEIGHT=1480

    phantomjs:
        image: cmfatih/phantomjs
        ports:
            - 8910
        entrypoint: phantomjs
        command: "--webdriver=8910"
