version: '2'

services:

    application:
        build: .
        working_dir: /var/www
        ports:
            - 80:80
        volumes:
            - ./opt/php/dev/conf.d:/usr/local/etc/php/conf.d
            - ./opt/php/dev/php.ini:/usr/local/etc/php/php.ini
            - ./opt/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
